export enum Routes {
  LOGIN = 'ENTRADA',
  REGISTER = 'REGISTRO',
  
  /*  */
  CLIENT_HOME = 'PRINCIPAL',
  HISTORIC_CLIENT = 'HISTORICO',
  CLIENT_VIEW_USER = 'ALTERAR_USUARIO_CLIENTE',
  CLIENT_USER_STACK = 'PILHA_USUARIO_CLIENTE',
  CLIENT_EDIT_USER = 'VISUALIZAR_USUARIO_CLIENTE',
  CLIENT_CONFIGURATION = 'CONFIGURACOES',
  // USERS = 'USUARIOS',
}

export enum UsuarioEnum {
  CLIENTE = 'CLIENTE',
  MOTORISTA = 'MOTORISTA',
}
