export enum Routes {
  LOGIN = 'ENTRADA',
  REGISTER = 'REGISTRO',
  HOME = 'PRINCIPAL',
  HISTORIC_CLIENT = 'HISTORICO',
  EDIT_USER = 'ALTERAR_USUARIO',
  CONFIGURATION = 'CONFIGURACOES',
  // USERS = 'USUARIOS',
}

export enum UsuarioEnum {
  CLIENTE = 'CLIENTE',
  MOTORISTA = 'MOTORISTA',
}
