export enum Routes {
  LOGIN = 'ENTRADA',
  REGISTER = 'REGISTRO',

  /* CLIENTE */
  CLIENT_HOME = 'PRINCIPAL',
  CLIENT_TAB_BOTTOM_HOME = 'PRINCIPAL_CLIENTE',
  CLIENT_TRUCK_ORDER = 'PEDIDO_SERVICO',
  CLIENT_WAITING_ORDER = 'PEDIDO_AGUARDANDO',
  CLIENT_PAYMENT_METHOD = 'METODO_PAGAMENTO_CLIENTE',
  HISTORIC_STACK_CLIENT = 'PILHA_HISTORICO',
  HISTORIC_CLIENT = 'CLIENTE_HISTORICO',
  HISTORIC_CLIENT_SINGLE = 'CLIENTE_HISTORICO_SINGULAR',
  CLIENT_VIEW_USER = 'VISUALIZAR_USUARIO_CLIENTE',
  CLIENT_USER_STACK = 'PILHA_USUARIO_CLIENTE',
  CLIENT_EDIT_USER = 'EDITAR_USUARIO_CLIENTE',
  CLIENT_CONFIGURATION = 'CLIENTE_CONFIGURACOES',
  CLIENT_SERVICE_AVAILABLE = 'SERVICO_DISPONIVEL',
  CLIENT_SERVICE_CONFIRMED = 'SERVICO_CONFIRMADO',

  // USERS = 'USUARIOS',
}

export enum UsuarioEnum {
  CLIENTE = 'CLIENTE',
  MOTORISTA = 'MOTORISTA',
}
